version: '3'
services:
  ui:
    build: .
    image: jeguzzi/thymioid:wlan
    network_mode: host
    privileged: true
    command: roslaunch --wait thymioid ui.launch
    volumes:
      - ./logs:/root/.ros/log:rw
      - /var/run/dbus:/var/run/dbus
      - /run/systemd:/run/systemd
      - /usr/bin/systemctl:/usr/bin/systemctl
      - /etc/systemd/system:/etc/systemd/system
      - /run/network:/run/network:r
