# Logitech F710 wireless controller
# Deadman (enable) button: Right Trigger
# D<>X button (located on the back panel) must be set to D
teleop:
  piloting:
    type: topic
    message_type: "geometry_msgs/Twist"
    topic_name: cmd_vel
    deadman_buttons: [7]
    axis_mappings:
      -
        axis: 3  # Right thumb stick (up/down)
        target: linear.x
        scale: 0.15
        offset: 0.0
      -
        axis: 0  # Left thumb stick (left/right)
        target: angular.z
        scale: 2.0
        offset: 0.0
  led_kit:
    type: topic
    message_type: "std_msgs/Float32"
    topic_name: led/gesture/kit
    deadman_buttons: [3]  # RT + Y
    axis_mappings:
      - axis: 1
        target: data
        scale: 1.0
        offset: 1.2
  led_alive:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: led/gesture/alive
    deadman_buttons: [1]  # RT + A
    axis_mappings: []
  led_off:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: led/gesture/off
    deadman_buttons: [0]  # RT + X
    axis_mappings: []
  body_led:
    type: topic
    message_type: "std_msgs/ColorRGBA"
    topic_name: led/body/top
    deadman_buttons: [6]  # RT + X
    axis_mappings:
      - axis: 0
        target: r
        scale: -0.5
        offset: 0.5
      - axis: 1
        target: g
        scale: 0.5
        offset: 0.5
      - axis: 2
        target: b
        scale: -0.5
        offset: 0.5
  play_sound_0:
    type: topic
    message_type: "thymio_msgs/SystemSound"
    topic_name: sound/play/system
    deadman_buttons: [6, 0]
    axis_mappings: []
    message_value:
      -
        target: sound
        value: 0
  play_sound_1:
    type: topic
    message_type: "thymio_msgs/SystemSound"
    topic_name: sound/play/system
    deadman_buttons: [6, 1]
    axis_mappings: []
    message_value:
      -
        target: sound
        value: 1
  play_sound_2:
    type: topic
    message_type: "thymio_msgs/SystemSound"
    topic_name: sound/play/system
    deadman_buttons: [6, 2]
    axis_mappings: []
    message_value:
      -
        target: sound
        value: 2
  play_sound_3:
    type: topic
    message_type: "thymio_msgs/SystemSound"
    topic_name: sound/play/system
    deadman_buttons: [6, 3]
    axis_mappings: []
    message_value:
      -
        target: sound
        value: 3
  play_sound_4:
    type: topic
    message_type: "thymio_msgs/SystemSound"
    topic_name: sound/play/system
    deadman_buttons: [6, 4]
    axis_mappings: []
    message_value:
      -
        target: sound
        value: 4
  play_sound_5:
    type: topic
    message_type: "thymio_msgs/SystemSound"
    topic_name: sound/play/system
    deadman_buttons: [6, 5]
    axis_mappings: []
    message_value:
      -
        target: sound
        value: 5
  play_sound_6:
    type: topic
    message_type: "thymio_msgs/SystemSound"
    topic_name: sound/play/system
    deadman_buttons: [6, 6]
    axis_mappings: []
    message_value:
      -
        target: sound
        value: 6
  play_sound_7:
    type: topic
    message_type: "thymio_msgs/SystemSound"
    topic_name: sound/play/system
    deadman_buttons: [6, 9]
    axis_mappings: []
    message_value:
      -
        target: sound
        value: 7
  play_sound_8:
    type: topic
    message_type: "thymio_msgs/SystemSound"
    topic_name: sound/play/system
    deadman_buttons: [6, 10]
    axis_mappings: []
    message_value:
      -
        target: sound
        value: -1
